"""
imgui_compat.py
Raw integer constants for pyimgui flags that vary by version.
Values taken from Dear ImGui 1.89 / pyimgui 1.4 headers.
Import these instead of relying on imgui.CONSTANT_NAME attributes.
"""

# ── TreeNode flags 
TREE_NODE_SELECTED                    = 1 << 0
TREE_NODE_FRAMED                      = 1 << 1
TREE_NODE_ALLOW_OVERLAP               = 1 << 2   # was ALLOW_ITEM_OVERLAP / ALLOW_OVERLAP_TITLE_AND_CONTENT
TREE_NODE_NO_TREE_PUSH_ON_OPEN        = 1 << 3
TREE_NODE_NO_AUTO_OPEN_ON_LOG         = 1 << 4
TREE_NODE_DEFAULT_OPEN                = 1 << 5
TREE_NODE_OPEN_ON_DOUBLE_CLICK        = 1 << 6
TREE_NODE_OPEN_ON_ARROW               = 1 << 7
TREE_NODE_LEAF                        = 1 << 8
TREE_NODE_BULLET                      = 1 << 9
TREE_NODE_FRAME_PADDING               = 1 << 10
TREE_NODE_SPAN_AVAIL_WIDTH            = 1 << 11
TREE_NODE_SPAN_FULL_WIDTH             = 1 << 12
TREE_NODE_NAV_LEFT_JUMPS_BACK_HERE    = 1 << 13
TREE_NODE_COLLAPSING_HEADER           = TREE_NODE_FRAMED | TREE_NODE_NO_TREE_PUSH_ON_OPEN | TREE_NODE_NO_AUTO_OPEN_ON_LOG

# ── Window flags 
WINDOW_NO_TITLE_BAR        = 1 << 0
WINDOW_NO_RESIZE           = 1 << 1
WINDOW_NO_MOVE             = 1 << 2
WINDOW_NO_SCROLLBAR        = 1 << 3
WINDOW_NO_SCROLL_WITH_MOUSE= 1 << 4
WINDOW_NO_COLLAPSE         = 1 << 5
WINDOW_ALWAYS_AUTO_RESIZE  = 1 << 6
WINDOW_NO_BACKGROUND       = 1 << 7
WINDOW_NO_SAVED_SETTINGS   = 1 << 8
WINDOW_NO_MOUSE_INPUTS     = 1 << 9
WINDOW_MENU_BAR            = 1 << 10
WINDOW_HORIZONTAL_SCROLLBAR= 1 << 11
WINDOW_NO_FOCUS_ON_APPEARING=1 << 12
WINDOW_NO_BRING_TO_DISPLAY_FRONT = 1 << 13
WINDOW_ALWAYS_VERTICAL_SCROLLBAR = 1 << 14
WINDOW_ALWAYS_HORIZONTAL_SCROLLBAR=1 << 15
WINDOW_ALWAYS_USE_WINDOW_PADDING = 1 << 16
WINDOW_NO_NAV_INPUTS       = 1 << 18
WINDOW_NO_NAV_FOCUS        = 1 << 19
WINDOW_UNSAVED_DOCUMENT    = 1 << 20
WINDOW_NO_NAV              = WINDOW_NO_NAV_INPUTS | WINDOW_NO_NAV_FOCUS
WINDOW_NO_DECORATION       = WINDOW_NO_TITLE_BAR | WINDOW_NO_RESIZE | WINDOW_NO_SCROLLBAR | WINDOW_NO_COLLAPSE
WINDOW_NO_INPUTS           = WINDOW_NO_MOUSE_INPUTS | WINDOW_NO_NAV_INPUTS | WINDOW_NO_NAV_FOCUS

# Convenient fixed-panel combo
WINDOW_FIXED = (
    WINDOW_NO_TITLE_BAR
    | WINDOW_NO_COLLAPSE
    | WINDOW_NO_RESIZE
    | WINDOW_NO_MOVE
    | WINDOW_NO_SCROLLBAR
    | WINDOW_NO_SAVED_SETTINGS
)
